class Mullm < Formula
  include Language::Python::Virtualenv

  desc "Local-first LLM router — 96.4% cost reduction, free tier first"
  homepage "https://mullm.com"
  url "https://github.com/0101technology/mullm/archive/refs/tags/v1.0.0.tar.gz"
  sha256 "FILL_AFTER_GITHUB_RELEASE"  # run: sha256sum mullm-1.0.0.tar.gz
  license "Apache-2.0"

  depends_on "python@3.12"
  depends_on "ollama" => :recommended

  resource "fastapi" do
    url "https://files.pythonhosted.org/packages/..."
    sha256 "..."
  end
  # remaining resources generated by: brew install homebrew/core/python-resource-helper
  # or: poet mullm  (from homebrew-poet: pip install homebrew-poet)

  def install
    virtualenv_install_with_resources
  end

  service do
    run [opt_bin/"mullm-server"]
    keep_alive true
    log_path var/"log/mullm.log"
    error_log_path var/"log/mullm.err"
    environment_variables PATH: std_service_path_env
  end

  test do
    # quick smoke test — no network needed
    system bin/"mullm", "--version"
  end
end
