"""Dialogue tree API — save/load/export/generate narrative dialogue trees.

Storage: ~/.mullm/dialogue/{name}.json

Export formats:
  mullm_native  — our own JSON (identity passthrough)
  ink           — Inkle Ink format (.ink text)
  yarn          — YarnSpinner JSON (.yarn.json)
  renpy         — Ren'Py script (.rpy)
  csv           — spreadsheet-friendly flat rows
"""

from __future__ import annotations

import csv
import io
import json
import re
import uuid
from pathlib import Path
from typing import Any

import httpx
from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel, Field

router = APIRouter(tags=["dialogue"])

# ── Storage ──────────────────────────────────────────────────────────────────

DIALOGUE_DIR = Path.home() / ".mullm" / "dialogue"


def _ensure_dir() -> Path:
    DIALOGUE_DIR.mkdir(parents=True, exist_ok=True)
    return DIALOGUE_DIR


def _sanitize_name(name: str) -> str:
    """Sanitize a tree name so it is safe as a filename. No path traversal."""
    # Strip .json suffix if present, then allow only alphanum/dash/underscore/dot
    raw = name.removesuffix(".json")
    safe = re.sub(r"[^A-Za-z0-9_.\-]", "-", raw).strip("-")
    safe = re.sub(r"-+", "-", safe)
    if not safe:
        raise HTTPException(status_code=400, detail="Invalid tree name")
    # Guard against traversal
    resolved = (_ensure_dir() / f"{safe}.json").resolve()
    if not str(resolved).startswith(str(_ensure_dir().resolve())):
        raise HTTPException(status_code=400, detail="Invalid tree name")
    return safe


# ── Native schema ─────────────────────────────────────────────────────────────

class ConditionModel(BaseModel):
    skill: str | None = None
    variable: str | None = None
    operator: str | None = None
    value: Any | None = None
    min: int | None = None


class ChoiceOption(BaseModel):
    label: str
    next: str | None = None
    condition: ConditionModel | None = None


class DialogueNode(BaseModel):
    id: str
    type: str  # npc | choice | condition | action | end
    speaker: str | None = None
    text: str | None = None
    portrait: str | None = None
    next: str | None = None
    options: list[ChoiceOption] | None = None
    variable: str | None = None
    operator: str | None = None
    value: Any | None = None
    action: str | None = None
    x: float | None = None
    y: float | None = None


class TreeMetadata(BaseModel):
    game: str = ""
    scene: str = ""
    tags: list[str] = Field(default_factory=list)


class DialogueTree(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    nodes: list[DialogueNode] = Field(default_factory=list)
    start_node: str | None = None
    variables: dict[str, Any] = Field(default_factory=dict)
    metadata: TreeMetadata = Field(default_factory=TreeMetadata)


class SaveRequest(BaseModel):
    tree: DialogueTree


class ExportRequest(BaseModel):
    tree: DialogueTree
    format: str = "mullm_native"


class GenerateRequest(BaseModel):
    description: str
    num_nodes: int = 6


# ── Helpers ───────────────────────────────────────────────────────────────────

EXPORT_FORMATS = {
    "mullm_native": "muLLM native JSON format",
    "ink":          "Inkle Ink scripting language (.ink)",
    "yarn":         "YarnSpinner JSON (.yarn.json)",
    "renpy":        "Ren'Py visual novel script (.rpy)",
    "csv":          "CSV spreadsheet for writers",
}


def _export_ink(tree: DialogueTree) -> str:
    """Convert dialogue tree to Inkle Ink format."""
    lines: list[str] = [f"// {tree.name}", "// Generated by muLLM", ""]
    node_map = {n.id: n for n in tree.nodes}

    visited: set[str] = set()
    order: list[str] = []
    if tree.start_node:
        stack = [tree.start_node]
        while stack:
            nid = stack.pop()
            if nid in visited:
                continue
            visited.add(nid)
            order.append(nid)
            node = node_map.get(nid)
            if node:
                if node.type == "choice" and node.options:
                    for opt in node.options:
                        if opt.next and opt.next not in visited:
                            stack.append(opt.next)
                elif node.next and node.next not in visited:
                    stack.append(node.next)
    # Emit unvisited nodes too
    for n in tree.nodes:
        if n.id not in visited:
            order.append(n.id)

    for nid in order:
        node = node_map.get(nid)
        if not node:
            continue
        lines.append(f"=== {nid} ===")
        if node.type == "npc":
            speaker = node.speaker or "NPC"
            text = node.text or ""
            lines.append(f"{speaker}: {text}")
            if node.next:
                lines.append(f"-> {node.next}")
            else:
                lines.append("-> END")
        elif node.type == "choice":
            for opt in (node.options or []):
                cond = ""
                if opt.condition and opt.condition.skill:
                    cond = f" {{skill >= {opt.condition.min or 0}}}"
                target = opt.next or "END"
                lines.append(f"* [{opt.label}]{cond}")
                lines.append(f"    -> {target}")
        elif node.type == "condition":
            var = node.variable or "flag"
            val = node.value or "true"
            lines.append(f"{{ {var} == {val}:")
            if node.next:
                lines.append(f"    -> {node.next}")
            lines.append("}")
        elif node.type == "action":
            lines.append(f"~ {node.action or 'action()'}")
            if node.next:
                lines.append(f"-> {node.next}")
        elif node.type == "end":
            lines.append("-> END")
        lines.append("")

    return "\n".join(lines)


def _export_yarn(tree: DialogueTree) -> dict[str, Any]:
    """Convert to YarnSpinner JSON format."""
    nodes_out = []
    for node in tree.nodes:
        body_lines: list[str] = []
        if node.type == "npc":
            speaker = node.speaker or "NPC"
            text = node.text or ""
            body_lines.append(f"{speaker}: {text}")
            if node.next:
                body_lines.append(f"-> {node.next}")
        elif node.type == "choice":
            for opt in (node.options or []):
                target = opt.next or ""
                cond = ""
                if opt.condition and opt.condition.skill:
                    cond = f" <<if $skill >= {opt.condition.min or 0}>>"
                body_lines.append(f"-> {opt.label}{cond}")
                body_lines.append(f"    <<jump {target}>>")
        elif node.type == "end":
            body_lines.append("<<stop>>")
        elif node.type == "action":
            body_lines.append(f"<<{node.action or 'action'} >>")
            if node.next:
                body_lines.append(f"<<jump {node.next}>>")

        nodes_out.append({
            "title": node.id,
            "tags": "",
            "body": "\n".join(body_lines),
        })

    return {
        "title": tree.name,
        "startNode": tree.start_node or "",
        "nodes": nodes_out,
    }


def _export_renpy(tree: DialogueTree) -> str:
    """Convert to Ren'Py .rpy script format."""
    lines: list[str] = [
        f'# {tree.name}',
        '# Generated by muLLM',
        '',
        'label start:',
    ]
    node_map = {n.id: n for n in tree.nodes}

    def emit_node(node: DialogueNode, indent: int = 1) -> None:
        pad = "    " * indent
        if node.type == "npc":
            speaker = node.speaker or "narrator"
            # Ren'Py: identifiers must be valid Python names
            char_id = re.sub(r"[^A-Za-z0-9_]", "_", speaker).lower()
            text = (node.text or "").replace('"', '\\"')
            lines.append(f'{pad}{char_id} "{text}"')
            if node.next and node.next in node_map:
                lines.append(f'{pad}jump {node.next}')
        elif node.type == "choice":
            lines.append(f'{pad}menu:')
            for opt in (node.options or []):
                cond = ""
                if opt.condition and opt.condition.skill:
                    cond = f' if {opt.condition.skill} >= {opt.condition.min or 0}'
                label_esc = opt.label.replace('"', '\\"')
                lines.append(f'{pad}    "{label_esc}"{cond}:')
                if opt.next:
                    lines.append(f'{pad}        jump {opt.next}')
        elif node.type == "end":
            lines.append(f'{pad}return')
        elif node.type == "action":
            lines.append(f'{pad}$ {node.action or "pass"}')
            if node.next:
                lines.append(f'{pad}jump {node.next}')

    # Emit as labels
    if tree.start_node and tree.start_node in node_map:
        lines.append(f'    jump {tree.start_node}')

    lines.append('')
    for node in tree.nodes:
        lines.append(f'label {node.id}:')
        emit_node(node)
        lines.append('')

    return "\n".join(lines)


def _export_csv(tree: DialogueTree) -> str:
    """Flat CSV: one row per node / option."""
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow([
        "node_id", "type", "speaker", "text",
        "option_label", "option_next", "option_condition",
        "next_node",
    ])
    for node in tree.nodes:
        if node.type == "choice" and node.options:
            for opt in node.options:
                cond_str = json.dumps(opt.condition.model_dump(exclude_none=True)) if opt.condition else ""
                writer.writerow([
                    node.id, node.type, "", "",
                    opt.label, opt.next or "", cond_str, "",
                ])
        else:
            writer.writerow([
                node.id, node.type,
                node.speaker or "", node.text or "",
                "", "", "", node.next or "",
            ])
    return buf.getvalue()


# ── Generate prompt ───────────────────────────────────────────────────────────

def _build_generate_prompt(description: str, num_nodes: int) -> str:
    return f"""Generate a dialogue tree for a game. Return ONLY valid JSON, no markdown, no explanation.

Description: {description}
Target node count: approximately {num_nodes} nodes

Use this exact JSON schema:
{{
  "id": "<uuid>",
  "name": "<short descriptive name>",
  "nodes": [
    {{
      "id": "n1",
      "type": "npc",
      "speaker": "<NPC name>",
      "text": "<what they say>",
      "portrait": null,
      "next": "<next node id or null>"
    }},
    {{
      "id": "choice_1",
      "type": "choice",
      "text": null,
      "options": [
        {{"label": "<player response>", "next": "<node id>", "condition": null}},
        {{"label": "<player response>", "next": "<node id>", "condition": null}}
      ]
    }}
  ],
  "start_node": "n1",
  "variables": {{}},
  "metadata": {{"game": "", "scene": "", "tags": []}}
}}

Node types allowed: npc, choice, condition, action, end
For condition nodes include: variable, operator, value fields.
For action nodes include: action field (a function call string).
For end nodes just set type to "end".
Make the dialogue feel natural for a video game. Return ONLY the JSON object."""


# ── Routes ────────────────────────────────────────────────────────────────────

@router.get("/api/dialogue/formats")
async def list_formats() -> JSONResponse:
    """List supported export formats."""
    return JSONResponse({
        "formats": [
            {"id": k, "label": v} for k, v in EXPORT_FORMATS.items()
        ]
    })


@router.get("/api/dialogue/list")
async def list_trees() -> JSONResponse:
    """List all saved dialogue trees (name + metadata)."""
    d = _ensure_dir()
    trees = []
    for f in sorted(d.glob("*.json")):
        try:
            data = json.loads(f.read_text())
            trees.append({
                "name": f.stem,
                "id": data.get("id", ""),
                "tree_name": data.get("name", f.stem),
                "node_count": len(data.get("nodes", [])),
                "modified": f.stat().st_mtime,
            })
        except Exception:
            trees.append({"name": f.stem, "id": "", "tree_name": f.stem, "node_count": 0, "modified": 0})
    return JSONResponse({"trees": trees})


@router.post("/api/dialogue/save")
async def save_tree(req: SaveRequest) -> JSONResponse:
    """Save a dialogue tree to disk."""
    d = _ensure_dir()
    safe = _sanitize_name(req.tree.name)
    path = d / f"{safe}.json"
    path.write_text(req.tree.model_dump_json(indent=2))
    return JSONResponse({"ok": True, "saved": safe})


@router.get("/api/dialogue/load/{name}")
async def load_tree(name: str) -> JSONResponse:
    """Load a dialogue tree by filename stem."""
    d = _ensure_dir()
    safe = _sanitize_name(name)
    path = d / f"{safe}.json"
    if not path.exists():
        raise HTTPException(status_code=404, detail=f"Tree '{safe}' not found")
    data = json.loads(path.read_text())
    return JSONResponse(data)


@router.delete("/api/dialogue/delete/{name}")
async def delete_tree(name: str) -> JSONResponse:
    """Delete a dialogue tree."""
    d = _ensure_dir()
    safe = _sanitize_name(name)
    path = d / f"{safe}.json"
    if not path.exists():
        raise HTTPException(status_code=404, detail=f"Tree '{safe}' not found")
    bak = path.with_suffix(".json.bak")
    path.rename(bak)
    return JSONResponse({"ok": True, "backed_up": str(bak)})


@router.post("/api/dialogue/export")
async def export_tree(req: ExportRequest) -> Response:
    """Export a dialogue tree to the requested format."""
    fmt = req.format.lower()
    if fmt not in EXPORT_FORMATS:
        raise HTTPException(status_code=400, detail=f"Unknown format '{fmt}'. Valid: {list(EXPORT_FORMATS)}")

    tree = req.tree

    if fmt == "mullm_native":
        return Response(
            content=tree.model_dump_json(indent=2),
            media_type="application/json",
            headers={"Content-Disposition": f'attachment; filename="{tree.name}.json"'},
        )

    if fmt == "ink":
        content = _export_ink(tree)
        return Response(
            content=content,
            media_type="text/plain",
            headers={"Content-Disposition": f'attachment; filename="{tree.name}.ink"'},
        )

    if fmt == "yarn":
        content = json.dumps(_export_yarn(tree), indent=2)
        return Response(
            content=content,
            media_type="application/json",
            headers={"Content-Disposition": f'attachment; filename="{tree.name}.yarn.json"'},
        )

    if fmt == "renpy":
        content = _export_renpy(tree)
        return Response(
            content=content,
            media_type="text/plain",
            headers={"Content-Disposition": f'attachment; filename="{tree.name}.rpy"'},
        )

    if fmt == "csv":
        content = _export_csv(tree)
        return Response(
            content=content,
            media_type="text/csv",
            headers={"Content-Disposition": f'attachment; filename="{tree.name}.csv"'},
        )

    raise HTTPException(status_code=400, detail=f"Unsupported export format: {fmt}")


@router.post("/api/dialogue/generate")
async def generate_tree(req: GenerateRequest) -> JSONResponse:
    """AI-generate a dialogue tree from a description using the local mullm LLM."""
    prompt = _build_generate_prompt(req.description, req.num_nodes)

    try:
        async with httpx.AsyncClient(timeout=60.0) as client:
            resp = await client.post(
                "http://127.0.0.1:6856/query",
                json={"content": prompt},
            )
            resp.raise_for_status()
            raw = resp.json()
    except httpx.HTTPError as exc:
        raise HTTPException(status_code=503, detail=f"mullm LLM unavailable: {exc}") from exc

    # Extract content — /query returns {"response": "..."} or {"content": "..."}
    content = raw.get("response") or raw.get("content") or raw.get("text") or str(raw)

    # Strip markdown code fences if present
    content = re.sub(r"^```(?:json)?\s*", "", content.strip(), flags=re.IGNORECASE)
    content = re.sub(r"\s*```$", "", content.strip(), flags=re.IGNORECASE)
    content = content.strip()

    try:
        tree_data = json.loads(content)
    except json.JSONDecodeError as exc:
        raise HTTPException(
            status_code=422,
            detail=f"LLM returned invalid JSON: {exc}. Raw: {content[:300]}",
        ) from exc

    # Ensure ID exists
    if "id" not in tree_data:
        tree_data["id"] = str(uuid.uuid4())

    # Validate via pydantic (will raise 422 on schema errors automatically)
    try:
        tree = DialogueTree.model_validate(tree_data)
    except Exception as exc:
        raise HTTPException(status_code=422, detail=f"Schema validation failed: {exc}") from exc

    return JSONResponse(tree.model_dump())
