"""Local model profile and swap planning API."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from router.backend_profiles import backend_profiles
from router.config import settings

router = APIRouter(prefix="/api/local-models", tags=["local-models"])


class LocalModelSelectRequest(BaseModel):
    profile_id: str
    apply: bool = False


def _all_profiles() -> list[dict[str, Any]]:
    return backend_profiles(include_experimental=True, include_nightly=True)


def _current_local_model() -> dict[str, Any]:
    return {
        "backend_priority": settings.local_backend_priority,
        "ollama_base_url": settings.ollama_base_url,
        "ollama_model": settings.ollama_model,
        "ollama_vision_model": settings.ollama_vision_model,
        "ollama_embed_model": settings.ollama_embed_model,
        "ollama_num_ctx": settings.ollama_num_ctx,
        "vram_limit_gb": settings.vram_limit_gb,
    }


def _profile_by_id(profile_id: str) -> dict[str, Any] | None:
    for profile in _all_profiles():
        if profile.get("id") == profile_id:
            return profile
    return None


def _write_profile_env(profile: dict[str, Any], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    env = profile.get("env") or {}
    lines = [
        "# Generated by muLLM local model setup.",
        "# Source this file before starting mullm-server, or copy values into .env.",
        f"MULLM_LOCAL_MODEL_PROFILE={profile['id']}",
    ]
    lines.extend(f"{key}={value}" for key, value in sorted(env.items()))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    path.chmod(0o600)


@router.get("/profiles")
async def list_local_model_profiles() -> dict[str, Any]:
    """Return model swap profiles and the currently loaded local settings."""
    return {
        "current": _current_local_model(),
        "profiles": _all_profiles(),
        "notes": [
            "TabbyAPI is the preferred ExLlamaV3 integration because it exposes an OpenAI-compatible API.",
            "Profile application writes a local env fragment; restart the server after sourcing or copying it.",
        ],
    }


@router.post("/select")
async def select_local_model_profile(req: LocalModelSelectRequest) -> dict[str, Any]:
    """Prepare or persist a local model profile selection."""
    profile = _profile_by_id(req.profile_id)
    if profile is None:
        raise HTTPException(status_code=404, detail="unknown local model profile")
    output_path = Path.home() / ".mullm" / "local-model.env"
    if req.apply:
        _write_profile_env(profile, output_path)
    return {
        "selected": profile,
        "applied": req.apply,
        "env_path": str(output_path),
        "restart_required": True,
        "next_step": "source the env fragment or copy values into .env, then restart mullm-server",
    }

